universe   = vanilla
executable = /home/shared/nitrates_new/NITRATES/do_llh_inFoV4realtime2.py 
arguments = --job_id $(Process)
error      = /home/shared/realtime_workdir/condor_log_error_files/condor_test_infovlog.err
output     = /home/shared/realtime_workdir/condor_log_error_files/condor_test_infovlog.out
log        = /home/shared/realtime_workdir/condor_log_error_files/condor_test_infovlog.log
getenv     = true
request_memory = 8000
request_cpus = 1
notification = never
queue 1
